# Generated by Django 3.2.25 on 2026-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeJoueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joueurNum', models.DecimalField(decimal_places=0, max_digits=10)),
                ('joueurNom', models.CharField(max_length=50)),
                ('joueurElim', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mancheNum', models.DecimalField(decimal_places=0, max_digits=10)),
                ('joueurNum', models.DecimalField(decimal_places=0, max_digits=10)),
                ('joueurScore', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
