# Generated by Django 3.2.25 on 2026-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listejoueurs',
            name='joueurElim',
            field=models.DecimalField(choices=[(1, 'Actif'), (2, 'Inactif')], decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='listejoueurs',
            name='joueurNum',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=10, unique=True),
        ),
    ]
