# Generated by Django 3.2.25 on 2026-09-10 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listejoueurs',
            name='joueurElim',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='joueurNum',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='joueurScore',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='tourNum',
        ),
        migrations.AddField(
            model_name='listejoueurs',
            name='couleur',
            field=models.CharField(blank=True, choices=[('#e74c3c', 'Rouge'), ('#3498db', 'Bleu'), ('#2ecc71', 'Vert'), ('#f1c40f', 'Jaune'), ('#9b59b6', 'Violet'), ('#e91e63', 'Rose'), ('#e67e22', 'Orange'), ('#2980b9', 'Bleu océan'), ('#27ae60', 'Vert émeraude'), ('#f39c12', 'Ambre'), ('#16a085', 'Turquoise'), ('#7f8c8d', 'Gris'), ('#f1948a', 'Corail'), ('#5dade2', 'Bleu ciel'), ('#58d68d', 'Vert menthe'), ('#bb8fce', 'Lavande'), ('#f8c471', 'Abricot'), ('#76d7c4', "Vert d'eau"), ('#af601a', 'Marron'), ('#f0b27a', 'Peche'), ('#a569bd', 'Améthyste'), ('#1f618d', 'Bleu marine')], max_length=10),
        ),
        migrations.AddField(
            model_name='partie',
            name='dateDebut',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partie',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partie',
            name='gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_gagnees', to='score.listejoueurs'),
        ),
        migrations.AddField(
            model_name='partie',
            name='typeJeu',
            field=models.CharField(choices=[('flechette', 'Fléchette'), ('president', 'Président'), ('dumble', 'Dumble')], default='flechette', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listejoueurs',
            name='joueurNum',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=10, unique=True),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valide', models.BooleanField(default=False)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='score.partie')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('casse', models.BooleanField(blank=True, null=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.listejoueurs')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='score.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ClassementPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveBigIntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.listejoueurs')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='score.partie')),
            ],
        ),
        migrations.CreateModel(
            name='ClassementManche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_arrivee', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=20)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.listejoueurs')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements_manche', to='score.tour')),
            ],
        ),
    ]
