# Generated by Django 3.2.25 on 2026-08-29 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20260829_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='partie',
            name='joueurNum',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='joueurScore',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='mancheNum',
        ),
        migrations.AddField(
            model_name='partie',
            name='dateDebut',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partie',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partie',
            name='gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_gagnees', to='score.listejoueurs'),
        ),
        migrations.AddField(
            model_name='partie',
            name='typeJeu',
            field=models.CharField(choices=[('flechette', 'Fléchette'), ('president', 'Président'), ('dumble', 'Dumble')], default='flechette', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScoreManche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.listejoueurs')),
                ('manche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='score.manche')),
            ],
        ),
        migrations.AddField(
            model_name='manche',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manches', to='score.partie'),
        ),
    ]
