# Generated by Django 3.2.25 on 2026-09-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20260905_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassementPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveBigIntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.listejoueurs')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='score.partie')),
            ],
        ),
    ]
