# Generated by Django 3.2.25 on 2026-08-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20260830_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremanche',
            name='casse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
