# Generated by Django 3.2.25 on 2026-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_classementpartie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
