# Generated by Django 3.2.25 on 2026-09-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listejoueurs',
            name='joueurElim',
        ),
        migrations.AddField(
            model_name='listejoueurs',
            name='couleur',
            field=models.CharField(blank=True, choices=[('#e74c3c', 'Rouge'), ('#3498db', 'Bleu'), ('#2ecc71', 'Vert'), ('#f1c40f', 'Jaune'), ('#9b59b6', 'Violet'), ('#e91e63', 'Rose'), ('#e67e22', 'Orange'), ('#1abc9c', 'Teal'), ('#c0392b', 'Rouge brique'), ('#2980b9', 'Bleu océan'), ('#27ae60', 'Vert émeraude'), ('#f39c12', 'Ambre'), ('#8e44ad', 'Violet foncé'), ('#d35400', 'Orange brûlé'), ('#16a085', 'Turquoise'), ('#2c3e50', 'Bleu nuit'), ('#7f8c8d', 'Gris'), ('#f1948a', 'Corail'), ('#5dade2', 'Bleu ciel'), ('#58d68d', 'Vert menthe'), ('#f7dc6f', 'Jaune pastel'), ('#bb8fce', 'Lavande'), ('#f8c471', 'Abricot'), ('#76d7c4', "Vert d'eau"), ('#af601a', 'Marron'), ('#d98880', 'Rose poudré'), ('#7dcea0', 'Vert sauge'), ('#f0b27a', 'Peche'), ('#a569bd', 'Améthyste'), ('#5499c7', 'Bleu acier'), ('#45b39d', 'Vert canard'), ('#eb984e', 'Mandarine'), ('#cb4335', 'Rouge tomate'), ('#48c9b0', 'Vert tropical'), ('#f4d03f', 'Or'), ('#a93226', 'Bordeaux'), ('#1f618d', 'Bleu marine')], max_length=10),
        ),
    ]
